version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.8.amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: host

  kafka:
    image: confluentinc/cp-kafka:5.5.8.amd64
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    network_mode: host

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.8.amd64
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:32181
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
    network_mode: host

  akhq:
    image: tchiotludo/akhq:0.21.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "host.docker.internal:29092"
              schema-registry:
                url: "http://localhost:8085"
        micronaut:
          server:
            port: 9900
    ports:
      - "9900:9900"
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    network_mode: host

#  influxdb:
#    image: influxdb:1.8
#    ports:
#      - "8086:8086"
#    environment:
#      - INFLUXDB_DB=k6
#    network_mode: host
#
#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_BASIC_ENABLED=false
#    volumes:
#      - ./grafana:/etc/grafana/provisioning/
#    network_mode: host

  k6-kafka:
    image: mostafamoradian/xk6-kafka:latest
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
      - "29092:29092"
    environment:
      - ADV_HOST=localhost
    network_mode: host
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    volumes:
      - ./k6:/scripts
#    image: grafana/k6:latest
#    networks:
#      - k6
#    ports:
#      - "6565:6565"
#    environment:
#      - K6_OUT=influxdb=http://influxdb:8086/k6
#    volumes:
#      - ./k6:/scripts
